### ISSUE TITLE
Cannot install with Python 3.12

### ISSUE THREAD

**Issue by prabhuomkar** [RapidAI/PaddleOCRModelConvert#14]
> [!NOTE]
> 请提供下述完整信息以便快速定位问题
> Please provide the following information to quickly locate the problem

**系统环境 (System Environment)** :  
Linux

**使用的是哪门语言的程序 (Which programing language)** :  
Python

**所使用语言相关版本信息 (Version)** :  
3.12

**使用当前库的版本 (Use current version)** :  
0.0.17

**可复现问题的demo和文件 (Demo of reproducible problems)** : 
N/A

**完整报错 (Complete Error Message)** :   
Cannot install this package with Python 3.12 running in the system. 

**可能的解决方案 (Possible solutions)** :  
Update setup.py to remove `<3.12` restriction.

**Comment by prabhuomkar** [comment]
@SWHL can we get an upgrade please?

**Comment by SWHL** [comment]
Technically, that's totally fine. I am just a little worried that the python3.12 version is unstable.

I would like to ask you, have you encountered any problems when using python3.12? Or is python3.12 stable enough?

**Comment by prabhuomkar** [comment]
> I would like to ask you, have you encountered any problems when using python3.12? Or is python3.12 stable enough?

It is pretty stable enough, I am running bunch of PyTorch models on 3.12 and other media related work, looking smooth so far.

**Comment by SWHL** [comment]
OK, I will upgrade this package to support python 3.12.
